version: "3.9"
services:
  backend:
    build:
      context: /home/burak/yenidenform
      dockerfile: Dockerfile.backend
    container_name: forum-backend
    ports:
      - "8000:8000"
    networks:
      - forum-network

  frontend:
    build:
      context: /home/burak/forumfrontend
      dockerfile: Dockerfile.frontend
    container_name: forum-frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend
    networks:
      - forum-network

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:8000" # Reverse proxy localhost:8000 olarak çalışacak
    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
